### ISSUE TITLE
Week 39 TODO list

### ISSUE THREAD

**Issue by Heartbroken-Git** [Heartbroken-Git/Project_Blood_Bowl#1]
# Week 39 TODO list
## @Heartbroken-Git
- [x] Place the Doxygen config file in the repo
- [x] Work on the two possibilities of GUI representation (One character art, 5x5 units) and choose one with @noel5550 
## @noel5550
- [x] Finish Dice class
- [x] Start working on the Pathing
- [x] Fix Player class
