### ISSUE TITLE
Week 42 TODO List

### ISSUE THREAD

**Issue by noel5550** [Heartbroken-Git/Project_Blood_Bowl#15]
# Week 42 TODO list

## General
- [ ] Close week 41

## @Heartbroken-Git 
- [ ] préparer le squelette du rapport LaTeX
- [ ] commencer à mettre en place Grid

## @noel5550
- [ ] réparer toutes les actions (ajouter les Dice.hpp, fixer l'héritage etc)
- [ ] commencer Player (avoir une version qui compile)
