### ISSUE TITLE
Week 45 TODO list 

### ISSUE THREAD

**Issue by noel5550** [Heartbroken-Git/Project_Blood_Bowl#18]
# Week 42 TODO list

## General
- [ ] Close week 42

## @Heartbroken-Git
- [ ] Implement Player class

## @noel5550
- [ ] Faire Playability, classes state jouabilité des Players
- [ ] Faire Wellbeing, classes state d'état de santé des Players
- [ ] Faire GameState, classes state d'état de jeu

**Comment by Heartbroken-Git** [comment]
@noel5550 Je te propose d'archiver ce repo comme on bosse plus du tout dessus. Je sais que tu voulais éventuellement t'y remettre pour essayer de le rendre fonctionnel donc avant de faire quoi que ce soit je voulais que tu me confirmes que tu ne comptes plus bosser dessus.

**Comment by noel5550** [comment]
En effet, archive le. Je m'en sert de temps en temps en tant que modèle
mais je ne vais pas continuer sur ca.

**Comment by Heartbroken-Git** [comment]
@noel5550 Entendu je l'archive, de toute façon quand il est archivé tu y as encore accès en lecture-seule :)
