### ISSUE TITLE
Week 40 TODO list

### ISSUE THREAD

**Issue by noel5550** [Heartbroken-Git/Project_Blood_Bowl#3]
# Week 40 TODO list
## General
- [x] Close TODO 39
## @Heartbroken-Git
- [x] Mettre les standards DOXYGEN
- [x] 1ere implémentation de Tile
- [x] Regarder pour intégrer Travis CI
## @noel5550
- [x] Diagramme UML des classes
- [x] hpp de Ball
- [x] hpp de l'interface Action et ses classe concrets
- [x] Implementer classe ActionPass
- ~~FACULTATIF Implementer Pathing class~~
